services:
  test-runner:
    image: rust:latest
    container_name: l3objectstorage-test-runner
    networks:
      testnet:
    dns:
      - 172.30.0.53
    volumes:
      - ../:/workspace
      - l3-cargo-registry:/usr/local/cargo/registry
      - l3-cargo-target:/workspace/target
    working_dir: /workspace
    environment:
      - TEST_ENDPOINT_URL=http://l3objectstorage-test:9000
      - TEST_VHOST_ENDPOINT_URL=http://s3.local:9000
      - TEST_FORCE_PATH_STYLE=false
    depends_on:
      - s3

volumes:
  l3-cargo-registry:
  l3-cargo-target:
