services:
  s3:
    environment:
      - LOCAL_S3_DOMAIN=

  dns-awsstyle:
    image: alpine
    container_name: l3objectstorage-dns-awsstyle
    networks:
      testnet:
        ipv4_address: 172.30.0.54
    volumes:
      - ./dnsmasq-awsstyle.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    command: sh -c "apk add --no-cache dnsmasq && dnsmasq -k"

  test-runner:
    image: rust:latest
    container_name: l3objectstorage-test-runner
    networks:
      testnet:
    dns:
      - 172.30.0.54
    volumes:
      - ../:/workspace
      - l3-cargo-registry:/usr/local/cargo/registry
      - l3-cargo-target:/workspace/target
    working_dir: /workspace
    environment:
      - TEST_ENDPOINT_URL=http://l3objectstorage-test:9000
      - TEST_AWSSTYLE_ENDPOINT_URL=http://s3.us-east-1.amazonaws.com:9000
      - TEST_SNS_ENDPOINT=http://sns:9911
      - TEST_SQS_ENDPOINT=http://sqs:9324
    depends_on:
      - s3
      - dns-awsstyle

volumes:
  l3-cargo-registry:
  l3-cargo-target:
